/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./templates/**/*.html",
    "./apps/**/*.py",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed": "#002113",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "on-secondary-fixed-variant": "#005236",
        "primary-fixed": "#d5e3ff",
        "tertiary-container": "#243448",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#38485d",
        "on-primary-fixed-variant": "#1f477b",
        "on-primary-container": "#799dd6",
        "inverse-primary": "#a7c8ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary": "#ffffff",
        "background": "#f7f9fb",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#003366",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "outline": "#737780",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c3c6d1",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#6cf8bb",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#3a5f94",
        "on-primary-fixed": "#001b3c",
        "on-tertiary-container": "#8c9cb5",
        "tertiary": "#0e1f32",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed": "#0b1c30",
        "on-surface-variant": "#43474f",
        "tertiary-fixed": "#d3e4fe",
        "secondary": "#006c49",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#00714d",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "primary": "#001e40",
        "primary-fixed-dim": "#a7c8ff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "stack-sm": "8px",
        "section-gap": "120px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin": "32px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-display": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-display": ["60px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/typography'),
  ],
}
