# Generated by Django 5.2.15 on 2026-07-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, help_text="e.g., 'home', 'about', 'services'", max_length=100)),
                ('section', models.CharField(db_index=True, help_text="e.g., 'hero', 'testimonials', 'footer'", max_length=100)),
                ('key', models.CharField(db_index=True, help_text="e.g., 'title', 'subtitle', 'image_1'", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Short description of where this content appears', max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Plain Text'), ('html', 'Rich Text (HTML)'), ('image', 'Image')], default='text', max_length=20)),
                ('text_value', models.TextField(blank=True, help_text='For plain text or HTML content', null=True)),
                ('image_value', models.ImageField(blank=True, help_text='For image uploads', null=True, upload_to='page_contents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ('page', 'section', 'key'),
                'unique_together': {('page', 'section', 'key')},
            },
        ),
    ]
