# Generated by Django 5.2.15 on 2026-06-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotLead',
            fields=[
            ],
            options={
                'verbose_name': 'Chatbot Lead',
                'verbose_name_plural': 'Chatbot Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact.contactrequest',),
        ),
    ]
