# Generated by Django 5.2.15 on 2026-07-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('User', 'User'), ('AI', 'AI'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
