# Generated by Django 5.2.15 on 2026-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Custom canonical link override if needed', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword targeted for optimization', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO Meta Description override'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO Title override', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social sharing Open Graph image override', null=True, upload_to='blog/og/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_score',
            field=models.IntegerField(default=0, help_text='Automated SEO readability/health score (0-100)'),
        ),
    ]
