# Generated by Django 5.2.15 on 2026-06-24 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_canonical_url_blogpost_focus_keyword_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, help_text='e.g. Co-Founder & Director', max_length=100)),
                ('expertise', models.CharField(blank=True, help_text='e.g. Enterprise Software Architect', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn profile URL')),
                ('organization', models.CharField(default='Blueshore Technologies', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Author biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
