# Generated by Django 5.2.15 on 2026-07-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Full GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Full X/Twitter profile URL'),
        ),
    ]
