# Generated by Django 5.2.15 on 2026-06-11 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_path', models.CharField(help_text="Path of the page, e.g., '/' or '/contact.html'", max_length=255, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/')),
                ('schema_markup', models.JSONField(blank=True, help_text='Structured JSON-LD schema blocks', null=True)),
                ('geo_what_is', models.TextField(blank=True)),
                ('geo_who_is', models.TextField(blank=True)),
                ('geo_why_matters', models.TextField(blank=True)),
                ('geo_takeaways', models.JSONField(blank=True, help_text='List of key takeaways', null=True)),
                ('geo_benefits', models.JSONField(blank=True, help_text='List of benefits (HTML lists allowed)', null=True)),
                ('faqs', models.JSONField(blank=True, help_text='FAQ items with question, answer, and details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata Entries',
            },
        ),
    ]
