# Generated by Django 5.2.15 on 2026-06-17 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0, help_text='Order in which FAQ is displayed')),
                ('is_active', models.BooleanField(default=True, help_text='Toggles visibility in AEO sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GEOBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_summary', models.TextField(help_text='Concise summary targeted directly at AI Search Overviews / LLM crawlers')),
                ('featured_answer', models.TextField(help_text='Short answer targeted at Google Featured Snippets')),
                ('what_is_this', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('who_is_it_for', models.TextField()),
                ('key_takeaways', models.TextField(help_text='Key takeaways, enter one per line')),
                ('eeat_proof_points', models.TextField(help_text='E-E-A-T proof points, enter one per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GEO Block',
                'verbose_name_plural': 'GEO Blocks',
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_name', models.CharField(help_text='Internal identifier or name of the page', max_length=255)),
                ('route', models.CharField(help_text="Path of the page, e.g., '/' or '/contact.html'", max_length=255, unique=True)),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('robots', models.CharField(default='index, follow', help_text="Robots meta directives (e.g. 'index, follow')", max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/')),
                ('schema_markup', models.JSONField(blank=True, help_text='Custom static JSON-LD schema blocks (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['page_name'],
            },
        ),
        migrations.DeleteModel(
            name='SEOMetadata',
        ),
        migrations.AddField(
            model_name='geoblock',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_block', to='seo.seopage'),
        ),
        migrations.AddField(
            model_name='faq',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='seo.seopage'),
        ),
    ]
