# Generated by Django 5.2.15 on 2026-06-17 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_faq_geoblock_seopage_delete_seometadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_agent', models.CharField(default='*', help_text="User-agent, e.g. '*', 'GPTBot', 'PerplexityBot'", max_length=255)),
                ('allow_paths', models.TextField(blank=True, help_text='Allowed paths, one per line (optional)')),
                ('disallow_paths', models.TextField(blank=True, help_text='Disallowed paths, one per line (optional)')),
                ('crawl_delay', models.IntegerField(blank=True, help_text='Crawl delay in seconds (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt Rule',
                'verbose_name_plural': 'Robots.txt Rules',
            },
        ),
    ]
