# Generated by Django 5.2.15 on 2026-07-09 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_robotsrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePillar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_slug', models.CharField(help_text="Unique slug, e.g., 'crm-integrations'", max_length=255, unique=True)),
                ('name', models.CharField(help_text="Clean service name, e.g. 'CRM Creation & Integrations'", max_length=255)),
                ('title', models.CharField(help_text='SEO Title', max_length=255)),
                ('description', models.TextField(help_text='SEO Meta Description')),
                ('tagline', models.CharField(help_text='Hero section tagline', max_length=255)),
                ('hero_bg_color', models.CharField(default='#3790ff', help_text='Hex code background highlight', max_length=50)),
                ('body_content', models.TextField(help_text='Primary pillar body copy (HTML/Markdown)')),
                ('process_json', models.JSONField(blank=True, help_text="List of process steps: [{'step': 1, 'title': '...', 'desc': '...'}]", null=True)),
                ('tech_stack_json', models.JSONField(blank=True, help_text="List of technologies: [{'name': '...', 'icon': '...'}]", null=True)),
                ('faq_json', models.JSONField(blank=True, help_text="List of FAQs: [{'q': '...', 'a': '...'}]", null=True)),
                ('testimonials_json', models.JSONField(blank=True, help_text="List of client testimonials: [{'client': '...', 'text': '...'}]", null=True)),
                ('case_studies_json', models.JSONField(blank=True, help_text="List of case studies: [{'title': '...', 'metric': '...', 'desc': '...'}]", null=True)),
                ('cta_text', models.CharField(default='Book Free Strategy Call', max_length=255)),
                ('cta_link', models.CharField(default='/contact.html', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Pillar Page',
                'verbose_name_plural': 'Service Pillar Pages',
                'ordering': ['name'],
            },
        ),
    ]
