# Generated by Django 5.2.17 on 2026-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_backlinkprospect_competitor_contentdecayqueue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepillar',
            name='cta_text',
            field=models.CharField(default='Get Started', max_length=255),
        ),
    ]
