# Generated by Django 5.2.15 on 2026-06-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
            ],
            options={
                'verbose_name': 'Lead / Contact Request',
                'verbose_name_plural': 'Leads / Contact Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact.contactrequest',),
        ),
    ]
