# Generated by Django 5.2.15 on 2026-06-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('crm', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_client', to='contact.contactrequest'),
        ),
    ]
