# Generated by Django 5.2.15 on 2026-07-04 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(default='Unknown', max_length=100)),
                ('device', models.CharField(default='Desktop', max_length=100)),
                ('os', models.CharField(default='Unknown', max_length=100)),
                ('screen_size', models.CharField(default='Unknown', max_length=50)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('first_visit', models.BooleanField(default=True)),
                ('is_returning', models.BooleanField(default=False)),
                ('current_url', models.TextField(default='')),
                ('current_page_title', models.CharField(default='Home', max_length=255)),
                ('previous_url', models.TextField(blank=True, null=True)),
                ('time_on_current_page', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0)),
                ('scroll_percentage', models.IntegerField(default=0)),
                ('max_scroll', models.IntegerField(default=0)),
                ('current_section', models.CharField(default='Hero', max_length=255)),
                ('active_tab', models.CharField(default='Visible', max_length=255)),
                ('is_idle', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('lead_score', models.IntegerField(default=0)),
                ('chat_mode', models.CharField(choices=[('AI', 'AI'), ('Human', 'Human'), ('Hybrid', 'Hybrid')], default='AI', max_length=20)),
                ('chat_status', models.CharField(choices=[('No Chat', 'No Chat'), ('Active', 'Active'), ('Idle', 'Idle'), ('Closed', 'Closed')], default='No Chat', max_length=20)),
                ('scored_milestones', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_sessions', to='contact.contactrequest')),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SessionReplayFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('events_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_frames', to='intelligence.visitorsession')),
            ],
            options={
                'verbose_name': 'Session Replay Frame',
                'verbose_name_plural': 'Session Replay Frames',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='intelligence.visitorsession')),
            ],
            options={
                'verbose_name': 'Visitor Timeline Event',
                'verbose_name_plural': 'Visitor Timeline Events',
                'ordering': ['created_at'],
            },
        ),
    ]
