# Generated by Django 5.2.15 on 2026-07-05 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drip Campaign',
                'verbose_name_plural': 'Drip Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(default=1)),
                ('delay_days', models.IntegerField(default=1, help_text='Number of days to wait before sending this step.')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Email body text/HTML.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='newsletter.dripcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Step',
                'verbose_name_plural': 'Campaign Steps',
                'ordering': ['step_number'],
            },
        ),
    ]
