# Generated by Django 5.2.15 on 2026-06-11 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Fintech', 'Fintech'), ('Logistics', 'Logistics'), ('Healthcare', 'Healthcare'), ('E-Commerce', 'E-Commerce'), ('Education', 'Education'), ('Real Estate', 'Real Estate')], max_length=100)),
                ('challenge', models.TextField()),
                ('strategy', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField()),
                ('metric_1_value', models.CharField(max_length=50)),
                ('metric_1_label', models.CharField(max_length=100)),
                ('metric_2_value', models.CharField(max_length=50)),
                ('metric_2_label', models.CharField(max_length=100)),
                ('image_dark', models.ImageField(blank=True, null=True, upload_to='portfolio/dark/')),
                ('image_light', models.ImageField(blank=True, null=True, upload_to='portfolio/light/')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
