# Generated by Django 5.2.15 on 2026-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='industry_tags',
            field=models.CharField(blank=True, help_text='Comma-separated industry tags', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO Meta Description override'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image override', null=True, upload_to='portfolio/og/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO Title override', max_length=255),
        ),
    ]
