# Generated by Django 5.2.15 on 2026-06-11 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('contract_type', models.CharField(choices=[('Contract', 'Contract'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default='Contract', max_length=50)),
                ('hours_per_week', models.CharField(blank=True, max_length=100)),
                ('hourly_rate_range', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Delhi NCR', 'Delhi NCR')], default='Remote', max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(help_text='Specialty selected (e.g. Frontend, Backend, UI/UX)', max_length=150)),
                ('experience', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('portfolio_url', models.URLField(max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, help_text='Null indicates general freelance roster application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.joblisting')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
