# Generated by Django 5.2.15 on 2026-06-17 19:50

import apps.careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.careers.models.get_resume_upload_path),
        ),
    ]
